# Generated by Django 6.0.4 on 2026-04-29 09:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bandara',
            fields=[
                ('iata_code', models.CharField(max_length=3, primary_key=True, serialize=False)),
                ('nama', models.CharField(max_length=100)),
                ('kota', models.CharField(max_length=100)),
                ('negara', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'BANDARA',
            },
        ),
        migrations.CreateModel(
            name='Maskapai',
            fields=[
                ('kode_maskapai', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('nama_maskapai', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'MASKAPAI',
            },
        ),
        migrations.CreateModel(
            name='ClaimMissingMiles',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tanggal_penerbangan', models.DateField()),
                ('flight_number', models.CharField(max_length=10)),
                ('nomor_tiket', models.CharField(max_length=20)),
                ('kelas_kabin', models.CharField(max_length=20)),
                ('pnr', models.CharField(max_length=10)),
                ('status_penerimaan', models.CharField(default='Menunggu', max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('bandara_asal', models.ForeignKey(db_column='bandara_asal', on_delete=django.db.models.deletion.CASCADE, related_name='asal', to='member.bandara')),
                ('bandara_tujuan', models.ForeignKey(db_column='bandara_tujuan', on_delete=django.db.models.deletion.CASCADE, related_name='tujuan', to='member.bandara')),
                ('email_member', models.ForeignKey(db_column='email_member', on_delete=django.db.models.deletion.CASCADE, to='accounts.member')),
                ('email_staf', models.ForeignKey(blank=True, db_column='email_staf', null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.staf')),
                ('maskapai', models.ForeignKey(db_column='maskapai', on_delete=django.db.models.deletion.CASCADE, to='member.maskapai')),
            ],
            options={
                'db_table': 'CLAIM_MISSING_MILES',
                'unique_together': {('email_member', 'flight_number', 'tanggal_penerbangan', 'nomor_tiket')},
            },
        ),
    ]
