# Generated by Django 6.0.4 on 2026-04-29 10:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('member', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('jumlah', models.IntegerField()),
                ('catatan', models.CharField(blank=True, max_length=255, null=True)),
                ('email_member_1', models.ForeignKey(db_column='email_member_1', on_delete=django.db.models.deletion.CASCADE, related_name='transfer_keluar', to='accounts.member')),
                ('email_member_2', models.ForeignKey(db_column='email_member_2', on_delete=django.db.models.deletion.CASCADE, related_name='transfer_masuk', to='accounts.member')),
            ],
            options={
                'db_table': 'TRANSFER',
                'unique_together': {('email_member_1', 'email_member_2', 'timestamp')},
            },
        ),
    ]
